# distance conversion factor
bohr_to_Angstrom = 0.529177
# radius of circle in which to find nearest neighbours
r_nn = 0.5  # A
# radius of circle with which to determine local density of neighbours for edge detection
subset_r_nn = 1  # A

# atom type based parameter: start area, depending on size it might preclude the search altogether
Atom_based_exclusion = {"C.1":             5,
                        "C.2":             2.5,
                        "C.3":             100,
                        "C.ar":            1.85,
                        "C.cat":           1.85,
                        "H.soft":          1.5,
                        "H.O":             1.5,
                        "H.N":             1.5,
                        "H.O.water":       3,
                        "H.N.group2":      3,
                        "H.N.ammonia":     3,
                        "N.1":             5,
                        "N.2":             1.85,
                        "N.3.ammonia":     3,
                        "N.3.primary":     3,
                        "N.3.secondary":   3,
                        "N.3.tertiary":    3,
                        "N.3.aniline":     3,
                        "N.ar":            3,
                        "N.ar.no_lp":      1.85,
                        "N.pl3":           1.85,
                        "N.pl3.am":        1.85,
                        "N.pl3.aniline":   1.85,
                        "N.pl3.primary":   1.85,
                        "N.pl3.secondary": 1.85,
                        "N.pl3.tertiary":  1.85,
                        "N.pl3.nitro":     1.85,
                        "N.4":             100,
                        "O.2":             3,
                        "O.2.carbonyl":    3,
                        "O.2.aldehyde":    3,
                        "O.2.po":          3,
                        "O.2.am":          3,
                        "O.2.sulfone":     3,
                        "O.2.sulfoxide":   3,
                        "O.2.one_lp":      3,
                        "O.2.other":       3,
                        "O.2.nitro":       3,
                        "O.2.noxide":      3,
                        "O.3":             3,
                        "O.3.water":       3,
                        "O.3.alcohol":     3,
                        "O.3.any":         3,
                        "O.co2":           3,
                        "P.3":             100,
                        "Si":              100,
                        "Se.3":            5,
                        "S.2":             5,
                        "S.2.phene":       5,
                        "S.2.ps":          5,
                        "S.3":             5,
                        "S.O":             5,
                        "S.O2":            100,
                        "S":               5,
                        "F":               5,
                        "Cl":              5,
                        "Br":              5,
                        "I":               5}
