import networkx as nx

# If the SSIP atom type is the same as the sybyl atom type,
# you should indicate the aipAtomType here as None

# HYDROGEN
nh = nx.Graph()
nh.add_node("N", elementType="N", aipAtomType=None)
nh.add_node("H", elementType="H", aipAtomType="H.N")
nh.add_edge("N", "H")

oh = nx.Graph()
oh.add_node("O", elementType="O", aipAtomType=None)
oh.add_node("H", elementType="H", aipAtomType="H.O")
oh.add_edge("O", "H")


softh = nx.Graph()
softh.add_node("soft", elementType=["!N", "!O"], aipAtomType=None)
softh.add_node("H", elementType="H", aipAtomType="H.soft")
softh.add_edge("soft", "H")

# OXYGEN AND NITROGEN
amide_n = nx.Graph()
amide_n.add_node("N", sybyl="N.am", aipAtomType="N.pl3.am")

amide = nx.Graph()
amide.add_node("C", elementType="C", aipAtomType=None)
amide.add_node("O", elementType="O", aipAtomType="O.2.am")
amide.add_node("N", elementType="N", aipAtomType=None)
amide.add_node("A1", aipAtomType=None)
amide.add_node("A2", aipAtomType=None)
amide.add_edge("C", "O", bondOrder=2)
amide.add_edge("C", "N")
amide.add_edge("A1", "N")
amide.add_edge("A2", "N")

vinylogous_amide = nx.Graph()
vinylogous_amide.add_node("C1", elementType="C", aipAtomType=None)
vinylogous_amide.add_node("O", elementType="O", aipAtomType="O.2.am")
vinylogous_amide.add_node("C2", elementType="C", aipAtomType=None)
vinylogous_amide.add_node("C3", elementType="C", aipAtomType=None)
vinylogous_amide.add_node("N", elementType="N", aipAtomType=None)
vinylogous_amide.add_edge("C1", "O", bondOrder=2)
vinylogous_amide.add_edge("C1", "C2", bondOrder=1)
vinylogous_amide.add_edge("C2", "C3", bondOrder=2)
vinylogous_amide.add_edge("C3", "N", bondOrder=1)

nitro = nx.Graph()
nitro.add_node("O1", elementType="O", aipAtomType="O.2.nitro")
nitro.add_node("N", elementType="N", aipAtomType="N.pl3.nitro")
nitro.add_node("O2", elementType="O", aipAtomType="O.2.nitro")
nitro.add_edge("O1", "N", bondOrder=2)
nitro.add_edge("O2", "N", bondOrder=1)

# OXYGEN
water = nx.Graph()
water.add_node("H1", elementType="H", aipAtomType="H.O.water")
water.add_node("O", elementType="O", aipAtomType="O.3.water")
water.add_node("H2", elementType="H", aipAtomType="H.O.water")
water.add_edge("H1", "O", bondOrder=1)
water.add_edge("H2", "O", bondOrder=1)

one_lp_1 = nx.Graph()
one_lp_1.add_node("A1", aipAtomType=None)
one_lp_1.add_node("O", sybyl="O.2", aipAtomType="O.2.one_lp")
one_lp_1.add_node("A2", aipAtomType=None)
one_lp_1.add_edge("A1", "O", bondOrder=1)
one_lp_1.add_edge("A2", "O", bondOrder=1)

one_lp_2 = nx.Graph()
one_lp_2.add_node("A1", aipAtomType=None)
one_lp_2.add_node("O", sybyl="O.3", aipAtomType="O.2.one_lp")
one_lp_2.add_node("A2", aipAtomType=None)
one_lp_2.add_node("X", elementType=["N", "O", "P", "S"], aipAtomType=None)
one_lp_2.add_edge("A1", "O", bondOrder=1)
one_lp_2.add_edge("A2", "O", bondOrder=1)
one_lp_2.add_edge("A1", "X", bondOrder=2)

aldehyde = nx.Graph()
aldehyde.add_node("C1", elementType="C", aipAtomType=None)
aldehyde.add_node("O", elementType="O", aipAtomType="O.2.aldehyde")
aldehyde.add_node("H", elementType="H", aipAtomType=None)
aldehyde.add_node("C2", elementType="C", aipAtomType=None)
aldehyde.add_edge("C1", "O", bondOrder=2)
aldehyde.add_edge("C1", "H")
aldehyde.add_edge("C1", "C2")

# The carbonyl graph needs to be matched after the amide graph
carbonyl = nx.Graph()
carbonyl.add_node("C", elementType="C", aipAtomType=None)
carbonyl.add_node("O", elementType="O", aipAtomType="O.2.carbonyl")
carbonyl.add_edge("C", "O", bondOrder=2)

po = nx.Graph()
po.add_node("P", elementType="P", aipAtomType=None)
po.add_node("O", elementType="O", aipAtomType="O.2.po")
po.add_edge("P", "O", bondOrder=2)

alcohol = nx.Graph()
alcohol.add_node("H1", sybyl="H", aipAtomType=None)
alcohol.add_node("O", sybyl="O.3", aipAtomType="O.3.alcohol")
alcohol.add_node("C", sybyl="C.3", aipAtomType=None)
alcohol.add_edge("H1", "O", bondOrder=1)
alcohol.add_edge("C", "O", bondOrder=1)

# The any O3 needs to be matched after the alcohol
noxide = nx.Graph()
noxide.add_node("N", elementType="N", aipAtomType="N.ar.no_lp")
noxide.add_node("O", sybyl="O.co2", aipAtomType="O.2.noxide")
noxide.add_edge("N", "O")

any_O3 = nx.Graph()
any_O3.add_node("A1", aipAtomType=None)
any_O3.add_node("O", elementType="O", aipAtomType="O.3.any")
any_O3.add_node("A2", aipAtomType=None)
any_O3.add_edge("A1", "O", bondOrder=1)
any_O3.add_edge("A2", "O", bondOrder=1)

epoxide = nx.Graph()
epoxide.add_node("A1", aipAtomType=None)
epoxide.add_node("O", elementType="O", aipAtomType="O.3.any")
epoxide.add_node("A2", aipAtomType=None)
epoxide.add_edge("A1", "O", bondOrder=1)
epoxide.add_edge("A2", "O", bondOrder=1)
epoxide.add_edge("A2", "A1", bondOrder=1)

sulfone = nx.Graph()
sulfone.add_node("S", sybyl="S.O2", aipAtomType=None)
sulfone.add_node("O1", sybyl="O.2", aipAtomType="O.2.sulfone")
sulfone.add_node("O2", sybyl="O.2", aipAtomType="O.2.sulfone")
sulfone.add_edge("S", "O1")
sulfone.add_edge("S", "O2")

sulfoxide = nx.Graph()
sulfoxide.add_node("S", sybyl="S.O", aipAtomType=None)
sulfoxide.add_node("O", sybyl="O.2", aipAtomType="O.2.sulfoxide")
sulfoxide.add_edge("S", "O")

selenone = nx.Graph()
selenone.add_node("Se", sybyl="Se.O2", aipAtomType=None)
selenone.add_node("O1", sybyl="O.2", aipAtomType="O.2.selenone")
selenone.add_node("O2", sybyl="O.2", aipAtomType="O.2.selenone")
selenone.add_edge("Se", "O1")
selenone.add_edge("Se", "O2")

selenoxide = nx.Graph()
selenoxide.add_node("Se", sybyl="Se.O", aipAtomType=None)
selenoxide.add_node("O", sybyl="O.2", aipAtomType="O.2.selenoxide")
selenoxide.add_edge("Se", "O")

# NITROGEN
not_pyridine = nx.Graph()
not_pyridine.add_node("a1", aipAtomType=None)
not_pyridine.add_node("N", sybyl="N.ar", aipAtomType="N.ar.no_lp")
not_pyridine.add_node("a2", aipAtomType=None)
not_pyridine.add_node("a3", aipAtomType=None)
not_pyridine.add_edge("a1", "N")
not_pyridine.add_edge("a2", "N")
not_pyridine.add_edge("a3", "N")

ammonia = nx.Graph()
ammonia.add_node("H1", elementType="H", aipAtomType="H.N.ammonia")
ammonia.add_node("N", sybyl="N.3", aipAtomType="N.3.ammonia")
ammonia.add_node("H2", elementType="H", aipAtomType="H.N.ammonia")
ammonia.add_node("H3", elementType="H", aipAtomType="H.N.ammonia")
ammonia.add_edge("H1", "N", bondOrder=1)
ammonia.add_edge("H2", "N", bondOrder=1)
ammonia.add_edge("H3", "N", bondOrder=1)


incorrectly_assigned_pl3 = nx.Graph()
incorrectly_assigned_pl3.add_node("A1", aipAtomType=None)
incorrectly_assigned_pl3.add_node("N", sybyl="N.pl3", aipAtomType="N.2")
incorrectly_assigned_pl3.add_node("A2",  aipAtomType=None)
incorrectly_assigned_pl3.add_edge("A1", "N", bondOrder=1)
incorrectly_assigned_pl3.add_edge("A2", "N", bondOrder=2)

primary_amine = nx.Graph()
# QUESTION: what should nitroamines be treated as?
primary_amine.add_node("H1", sybyl="H", aipAtomType=None)
primary_amine.add_node("N", sybyl="N.3", aipAtomType="N.3.primary")
primary_amine.add_node("H2", sybyl="H", aipAtomType=None)
primary_amine.add_node("C3", sybyl="!H", aipAtomType=None)
primary_amine.add_edge("H1", "N", bondOrder=1)
primary_amine.add_edge("H2", "N", bondOrder=1)
primary_amine.add_edge("C3", "N", bondOrder=1)

secondary_amine = nx.Graph()
secondary_amine.add_node("H1", sybyl="H", aipAtomType=None)
secondary_amine.add_node("N",  sybyl="N.3",  aipAtomType="N.3.secondary")
secondary_amine.add_node("A2", sybyl="!H", aipAtomType=None)
secondary_amine.add_node("C3", sybyl="!H", aipAtomType=None)
secondary_amine.add_edge("H1", "N", bondOrder=1)
secondary_amine.add_edge("A2", "N", bondOrder=1)
secondary_amine.add_edge("C3", "N", bondOrder=1)

tertiary_amine = nx.Graph()
tertiary_amine.add_node("A1",  sybyl="!H", aipAtomType=None)
tertiary_amine.add_node("N",  sybyl="N.3",  aipAtomType="N.3.tertiary")
tertiary_amine.add_node("A2", sybyl="!H", aipAtomType=None)
tertiary_amine.add_node("A3",  sybyl="!H", aipAtomType=None)
tertiary_amine.add_edge("A1", "N", bondOrder=1)
tertiary_amine.add_edge("A2", "N", bondOrder=1)
tertiary_amine.add_edge("A3", "N", bondOrder=1)

planar_aniline = nx.Graph()
planar_aniline.add_node("A1",  sybyl="C.ar", aipAtomType="C.ar")
planar_aniline.add_node("N",  sybyl="N.pl3",  aipAtomType="N.pl3.aniline")
planar_aniline.add_node("A2", aipAtomType=None)
planar_aniline.add_node("A3", aipAtomType=None)
planar_aniline.add_edge("A1", "N", bondOrder=1)
planar_aniline.add_edge("A2", "N", bondOrder=1)
planar_aniline.add_edge("A3", "N", bondOrder=1)

primary_pl3_nitrogen = nx.Graph()
primary_pl3_nitrogen.add_node("H1", sybyl="H", aipAtomType=None)
primary_pl3_nitrogen.add_node("N", sybyl="N.pl3", aipAtomType="N.pl3.primary")
primary_pl3_nitrogen.add_node("H2", sybyl="H", aipAtomType=None)
primary_pl3_nitrogen.add_node("C3", sybyl="!H", aipAtomType=None)
primary_pl3_nitrogen.add_edge("H1", "N", bondOrder=1)
primary_pl3_nitrogen.add_edge("H2", "N", bondOrder=1)
primary_pl3_nitrogen.add_edge("C3", "N", bondOrder=1)

secondary_pl3_nitrogen = nx.Graph()
secondary_pl3_nitrogen.add_node("H1", sybyl="H", aipAtomType=None)
secondary_pl3_nitrogen.add_node(
    "N",  sybyl="N.pl3",  aipAtomType="N.pl3.secondary")
secondary_pl3_nitrogen.add_node("A2", sybyl="!H", aipAtomType=None)
secondary_pl3_nitrogen.add_node("C3", sybyl="!H", aipAtomType=None)
secondary_pl3_nitrogen.add_edge("H1", "N", bondOrder=1)
secondary_pl3_nitrogen.add_edge("A2", "N", bondOrder=1)
secondary_pl3_nitrogen.add_edge("C3", "N", bondOrder=1)

# This graph needs to be matched after the nitro
tertiary_pl3_nitrogen = nx.Graph()
tertiary_pl3_nitrogen.add_node("A1",  sybyl="!H", aipAtomType=None)
tertiary_pl3_nitrogen.add_node(
    "N",  sybyl="N.pl3",  aipAtomType="N.pl3.tertiary")
tertiary_pl3_nitrogen.add_node("A2", sybyl="!H", aipAtomType=None)
tertiary_pl3_nitrogen.add_node("A3",  sybyl="!H", aipAtomType=None)
tertiary_pl3_nitrogen.add_edge("A1", "N", bondOrder=1)
tertiary_pl3_nitrogen.add_edge("A2", "N", bondOrder=1)
tertiary_pl3_nitrogen.add_edge("A3", "N", bondOrder=1)

quaternary_nitrogen = nx.Graph()
quaternary_nitrogen.add_node("N",  sybyl="N.4",  aipAtomType="N.4")
quaternary_nitrogen.add_node("A1", aipAtomType=None)
quaternary_nitrogen.add_node("A2", aipAtomType=None)
quaternary_nitrogen.add_node("A3", aipAtomType=None)
quaternary_nitrogen.add_node("A4", aipAtomType=None)
quaternary_nitrogen.add_edge("A1", "N", bondOrder=1)
quaternary_nitrogen.add_edge("A2", "N", bondOrder=1)
quaternary_nitrogen.add_edge("A3", "N", bondOrder=1)
quaternary_nitrogen.add_edge("A4", "N", bondOrder=1)

n_sulfoxide = nx.Graph()
n_sulfoxide.add_node("S", sybyl="S.3", aipAtomType="S.0")
n_sulfoxide.add_node("N", sybyl="N.2", aipAtomType="N.2")
n_sulfoxide.add_edge("S", "N", bondOrder=2)

# SULFUR AND SELENIUM AND OTHERS
ps = nx.Graph()
ps.add_node("P", elementType="P", aipAtomType="P.3")
ps.add_node("S", elementType="S", aipAtomType="S.2.ps")
ps.add_edge("P", "S", bondOrder=2)

phene = nx.Graph()
phene.add_node("A1", aipAtomType=None)
phene.add_node("S", sybyl="S.2", aipAtomType="S.2.phene")
phene.add_node("A2", aipAtomType=None)
phene.add_edge("A1", "S", bondOrder=1)
phene.add_edge("A2", "S", bondOrder=1)

quaternary_sulfur = nx.Graph()
quaternary_sulfur.add_node("S",  sybyl="S.3",  aipAtomType="S.4")
quaternary_sulfur.add_node("A1", aipAtomType=None)
quaternary_sulfur.add_node("A2", aipAtomType=None)
quaternary_sulfur.add_node("A3", aipAtomType=None)
quaternary_sulfur.add_node("A4", aipAtomType=None)
quaternary_sulfur.add_edge("A1", "S", bondOrder=1)
quaternary_sulfur.add_edge("A2", "S", bondOrder=1)
quaternary_sulfur.add_edge("A3", "S", bondOrder=1)
quaternary_sulfur.add_edge("A4", "S", bondOrder=1)

phos = nx.Graph()
phos.add_node("P", elementType="P.3", aipAtomType=None)
phos.add_node("A1", aipAtomType=None)
phos.add_node("A2", aipAtomType=None)
phos.add_node("A3", aipAtomType=None)
phos.add_edge("A1", "P", bondOrder=1)
phos.add_edge("A2", "P", bondOrder=1)
phos.add_edge("A3", "P", bondOrder=1)

silicon = nx.Graph()
silicon.add_node("Si", elementType="Si", aipAtomType=None)
silicon.add_node("A1", aipAtomType=None)
silicon.add_node("A2", aipAtomType=None)
silicon.add_node("A3", aipAtomType=None)
silicon.add_edge("A1", "Si", bondOrder=1)
silicon.add_edge("A2", "Si", bondOrder=1)
silicon.add_edge("A3", "Si", bondOrder=1)

special_car = nx.Graph()
special_car.add_node("C1", sybyl="C.ar", aipAtomType="C.ar_special")
special_car.add_node("C2", sybyl="C.ar", aipAtomType="C.ar_special")
special_car.add_edge("C1", "C2", bondOrder=1)
special_car = nx.Graph()

special_car2 = nx.Graph()
special_car2.add_node("C1", sybyl="C.ar", aipAtomType="C.ar_special")
special_car2.add_node("C2", sybyl="C.3", aipAtomType=None)
special_car2.add_edge("C1", "C2", bondOrder=1)

special_c2 = nx.Graph()
special_c2.add_node("C1", sybyl="C.ar", aipAtomType=None)
special_c2.add_node("C2", sybyl="C.2", aipAtomType="C.2_special")
special_c2.add_edge("C1", "C2", bondOrder=1)


special_c1 = nx.Graph()
special_c1.add_node("C1", sybyl="C.ar", aipAtomType=None)
special_c1.add_node("C2", sybyl="C.1", aipAtomType="C.1_special")
special_c1.add_edge("C1", "C2", bondOrder=1)


special_nam = nx.Graph()
special_nam.add_node("N1", sybyl="N.am", aipAtomType="N.pl3.am_special")
special_nam.add_node("C2", sybyl="C.3", aipAtomType=None)
special_nam.add_node("C3", sybyl="C.3", aipAtomType=None)
special_nam.add_edge("N1", "C2", bondOrder=1)
special_nam.add_edge("N1", "C3", bondOrder=1)


special_o3 = nx.Graph()
special_o3.add_node("O1", sybyl="O.3", aipAtomType="O.3_special")
special_o3.add_node("C2", sybyl="C.3", aipAtomType=None)
special_o3.add_node("C3", sybyl="C.3", aipAtomType=None)
special_o3.add_edge("O1", "C2", bondOrder=1)
special_o3.add_edge("O1", "C3", bondOrder=1)
